# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3c2ce784dbb43d6bdff6197f628694b3b4ed8772a0bea161f128fc2b03ae77ec254c478af318f2879fdb3c90794267b8684794ad395f3bb539bc37f547a7a65

test:
  secret_key_base: 90260690e90953d558071a92587552bca1a9e66e36a8563161ff74c2942ea49aa1c4411ac9fbb897303e1b492e7001f11f9f0a5ef2425edc9cebd7e829573b16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
